# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yirade/Documents/POO-Game

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yirade/Documents/POO-Game

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/yirade/Documents/POO-Game/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\" \"bin\" \"devel\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yirade/Documents/POO-Game/CMakeFiles /home/yirade/Documents/POO-Game//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yirade/Documents/POO-Game/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named game

# Build rule for target.
game: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 game
.PHONY : game

# fast build rule for target.
game/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/build
.PHONY : game/fast

#=============================================================================
# Target rules for targets named sfml-system

# Build rule for target.
sfml-system: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfml-system
.PHONY : sfml-system

# fast build rule for target.
sfml-system/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sfml-build/src/SFML/System/CMakeFiles/sfml-system.dir/build.make _deps/sfml-build/src/SFML/System/CMakeFiles/sfml-system.dir/build
.PHONY : sfml-system/fast

#=============================================================================
# Target rules for targets named sfml-window

# Build rule for target.
sfml-window: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfml-window
.PHONY : sfml-window

# fast build rule for target.
sfml-window/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sfml-build/src/SFML/Window/CMakeFiles/sfml-window.dir/build.make _deps/sfml-build/src/SFML/Window/CMakeFiles/sfml-window.dir/build
.PHONY : sfml-window/fast

#=============================================================================
# Target rules for targets named sfml-network

# Build rule for target.
sfml-network: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfml-network
.PHONY : sfml-network

# fast build rule for target.
sfml-network/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sfml-build/src/SFML/Network/CMakeFiles/sfml-network.dir/build.make _deps/sfml-build/src/SFML/Network/CMakeFiles/sfml-network.dir/build
.PHONY : sfml-network/fast

#=============================================================================
# Target rules for targets named sfml-graphics

# Build rule for target.
sfml-graphics: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfml-graphics
.PHONY : sfml-graphics

# fast build rule for target.
sfml-graphics/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sfml-build/src/SFML/Graphics/CMakeFiles/sfml-graphics.dir/build.make _deps/sfml-build/src/SFML/Graphics/CMakeFiles/sfml-graphics.dir/build
.PHONY : sfml-graphics/fast

#=============================================================================
# Target rules for targets named sfml-audio

# Build rule for target.
sfml-audio: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfml-audio
.PHONY : sfml-audio

# fast build rule for target.
sfml-audio/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sfml-build/src/SFML/Audio/CMakeFiles/sfml-audio.dir/build.make _deps/sfml-build/src/SFML/Audio/CMakeFiles/sfml-audio.dir/build
.PHONY : sfml-audio/fast

source/main.o: source/main.cpp.o
.PHONY : source/main.o

# target to build an object file
source/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/source/main.cpp.o
.PHONY : source/main.cpp.o

source/main.i: source/main.cpp.i
.PHONY : source/main.i

# target to preprocess a source file
source/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/source/main.cpp.i
.PHONY : source/main.cpp.i

source/main.s: source/main.cpp.s
.PHONY : source/main.s

# target to generate assembly for a file
source/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/source/main.cpp.s
.PHONY : source/main.cpp.s

source/scenes/Character.o: source/scenes/Character.cpp.o
.PHONY : source/scenes/Character.o

# target to build an object file
source/scenes/Character.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/source/scenes/Character.cpp.o
.PHONY : source/scenes/Character.cpp.o

source/scenes/Character.i: source/scenes/Character.cpp.i
.PHONY : source/scenes/Character.i

# target to preprocess a source file
source/scenes/Character.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/source/scenes/Character.cpp.i
.PHONY : source/scenes/Character.cpp.i

source/scenes/Character.s: source/scenes/Character.cpp.s
.PHONY : source/scenes/Character.s

# target to generate assembly for a file
source/scenes/Character.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/source/scenes/Character.cpp.s
.PHONY : source/scenes/Character.cpp.s

source/scenes/Game.o: source/scenes/Game.cpp.o
.PHONY : source/scenes/Game.o

# target to build an object file
source/scenes/Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/source/scenes/Game.cpp.o
.PHONY : source/scenes/Game.cpp.o

source/scenes/Game.i: source/scenes/Game.cpp.i
.PHONY : source/scenes/Game.i

# target to preprocess a source file
source/scenes/Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/source/scenes/Game.cpp.i
.PHONY : source/scenes/Game.cpp.i

source/scenes/Game.s: source/scenes/Game.cpp.s
.PHONY : source/scenes/Game.s

# target to generate assembly for a file
source/scenes/Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/source/scenes/Game.cpp.s
.PHONY : source/scenes/Game.cpp.s

source/scenes/title_screen.o: source/scenes/title_screen.cpp.o
.PHONY : source/scenes/title_screen.o

# target to build an object file
source/scenes/title_screen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/source/scenes/title_screen.cpp.o
.PHONY : source/scenes/title_screen.cpp.o

source/scenes/title_screen.i: source/scenes/title_screen.cpp.i
.PHONY : source/scenes/title_screen.i

# target to preprocess a source file
source/scenes/title_screen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/source/scenes/title_screen.cpp.i
.PHONY : source/scenes/title_screen.cpp.i

source/scenes/title_screen.s: source/scenes/title_screen.cpp.s
.PHONY : source/scenes/title_screen.s

# target to generate assembly for a file
source/scenes/title_screen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/source/scenes/title_screen.cpp.s
.PHONY : source/scenes/title_screen.cpp.s

source/scenes/utils/AnimatedObject.o: source/scenes/utils/AnimatedObject.cpp.o
.PHONY : source/scenes/utils/AnimatedObject.o

# target to build an object file
source/scenes/utils/AnimatedObject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/source/scenes/utils/AnimatedObject.cpp.o
.PHONY : source/scenes/utils/AnimatedObject.cpp.o

source/scenes/utils/AnimatedObject.i: source/scenes/utils/AnimatedObject.cpp.i
.PHONY : source/scenes/utils/AnimatedObject.i

# target to preprocess a source file
source/scenes/utils/AnimatedObject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/source/scenes/utils/AnimatedObject.cpp.i
.PHONY : source/scenes/utils/AnimatedObject.cpp.i

source/scenes/utils/AnimatedObject.s: source/scenes/utils/AnimatedObject.cpp.s
.PHONY : source/scenes/utils/AnimatedObject.s

# target to generate assembly for a file
source/scenes/utils/AnimatedObject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/source/scenes/utils/AnimatedObject.cpp.s
.PHONY : source/scenes/utils/AnimatedObject.cpp.s

source/scenes/utils/Button.o: source/scenes/utils/Button.cpp.o
.PHONY : source/scenes/utils/Button.o

# target to build an object file
source/scenes/utils/Button.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/source/scenes/utils/Button.cpp.o
.PHONY : source/scenes/utils/Button.cpp.o

source/scenes/utils/Button.i: source/scenes/utils/Button.cpp.i
.PHONY : source/scenes/utils/Button.i

# target to preprocess a source file
source/scenes/utils/Button.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/source/scenes/utils/Button.cpp.i
.PHONY : source/scenes/utils/Button.cpp.i

source/scenes/utils/Button.s: source/scenes/utils/Button.cpp.s
.PHONY : source/scenes/utils/Button.s

# target to generate assembly for a file
source/scenes/utils/Button.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/source/scenes/utils/Button.cpp.s
.PHONY : source/scenes/utils/Button.cpp.s

source/scenes/utils/CollisionElement.o: source/scenes/utils/CollisionElement.cpp.o
.PHONY : source/scenes/utils/CollisionElement.o

# target to build an object file
source/scenes/utils/CollisionElement.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/source/scenes/utils/CollisionElement.cpp.o
.PHONY : source/scenes/utils/CollisionElement.cpp.o

source/scenes/utils/CollisionElement.i: source/scenes/utils/CollisionElement.cpp.i
.PHONY : source/scenes/utils/CollisionElement.i

# target to preprocess a source file
source/scenes/utils/CollisionElement.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/source/scenes/utils/CollisionElement.cpp.i
.PHONY : source/scenes/utils/CollisionElement.cpp.i

source/scenes/utils/CollisionElement.s: source/scenes/utils/CollisionElement.cpp.s
.PHONY : source/scenes/utils/CollisionElement.s

# target to generate assembly for a file
source/scenes/utils/CollisionElement.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/source/scenes/utils/CollisionElement.cpp.s
.PHONY : source/scenes/utils/CollisionElement.cpp.s

source/scenes/utils/DrawnButton.o: source/scenes/utils/DrawnButton.cpp.o
.PHONY : source/scenes/utils/DrawnButton.o

# target to build an object file
source/scenes/utils/DrawnButton.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/source/scenes/utils/DrawnButton.cpp.o
.PHONY : source/scenes/utils/DrawnButton.cpp.o

source/scenes/utils/DrawnButton.i: source/scenes/utils/DrawnButton.cpp.i
.PHONY : source/scenes/utils/DrawnButton.i

# target to preprocess a source file
source/scenes/utils/DrawnButton.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/source/scenes/utils/DrawnButton.cpp.i
.PHONY : source/scenes/utils/DrawnButton.cpp.i

source/scenes/utils/DrawnButton.s: source/scenes/utils/DrawnButton.cpp.s
.PHONY : source/scenes/utils/DrawnButton.s

# target to generate assembly for a file
source/scenes/utils/DrawnButton.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/source/scenes/utils/DrawnButton.cpp.s
.PHONY : source/scenes/utils/DrawnButton.cpp.s

source/scenes/utils/DrawnImage.o: source/scenes/utils/DrawnImage.cpp.o
.PHONY : source/scenes/utils/DrawnImage.o

# target to build an object file
source/scenes/utils/DrawnImage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/source/scenes/utils/DrawnImage.cpp.o
.PHONY : source/scenes/utils/DrawnImage.cpp.o

source/scenes/utils/DrawnImage.i: source/scenes/utils/DrawnImage.cpp.i
.PHONY : source/scenes/utils/DrawnImage.i

# target to preprocess a source file
source/scenes/utils/DrawnImage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/source/scenes/utils/DrawnImage.cpp.i
.PHONY : source/scenes/utils/DrawnImage.cpp.i

source/scenes/utils/DrawnImage.s: source/scenes/utils/DrawnImage.cpp.s
.PHONY : source/scenes/utils/DrawnImage.s

# target to generate assembly for a file
source/scenes/utils/DrawnImage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/source/scenes/utils/DrawnImage.cpp.s
.PHONY : source/scenes/utils/DrawnImage.cpp.s

source/scenes/utils/DrawnText.o: source/scenes/utils/DrawnText.cpp.o
.PHONY : source/scenes/utils/DrawnText.o

# target to build an object file
source/scenes/utils/DrawnText.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/source/scenes/utils/DrawnText.cpp.o
.PHONY : source/scenes/utils/DrawnText.cpp.o

source/scenes/utils/DrawnText.i: source/scenes/utils/DrawnText.cpp.i
.PHONY : source/scenes/utils/DrawnText.i

# target to preprocess a source file
source/scenes/utils/DrawnText.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/source/scenes/utils/DrawnText.cpp.i
.PHONY : source/scenes/utils/DrawnText.cpp.i

source/scenes/utils/DrawnText.s: source/scenes/utils/DrawnText.cpp.s
.PHONY : source/scenes/utils/DrawnText.s

# target to generate assembly for a file
source/scenes/utils/DrawnText.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/source/scenes/utils/DrawnText.cpp.s
.PHONY : source/scenes/utils/DrawnText.cpp.s

source/scenes/utils/DynamicTile.o: source/scenes/utils/DynamicTile.cpp.o
.PHONY : source/scenes/utils/DynamicTile.o

# target to build an object file
source/scenes/utils/DynamicTile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/source/scenes/utils/DynamicTile.cpp.o
.PHONY : source/scenes/utils/DynamicTile.cpp.o

source/scenes/utils/DynamicTile.i: source/scenes/utils/DynamicTile.cpp.i
.PHONY : source/scenes/utils/DynamicTile.i

# target to preprocess a source file
source/scenes/utils/DynamicTile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/source/scenes/utils/DynamicTile.cpp.i
.PHONY : source/scenes/utils/DynamicTile.cpp.i

source/scenes/utils/DynamicTile.s: source/scenes/utils/DynamicTile.cpp.s
.PHONY : source/scenes/utils/DynamicTile.s

# target to generate assembly for a file
source/scenes/utils/DynamicTile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/source/scenes/utils/DynamicTile.cpp.s
.PHONY : source/scenes/utils/DynamicTile.cpp.s

source/scenes/utils/Enemy.o: source/scenes/utils/Enemy.cpp.o
.PHONY : source/scenes/utils/Enemy.o

# target to build an object file
source/scenes/utils/Enemy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/source/scenes/utils/Enemy.cpp.o
.PHONY : source/scenes/utils/Enemy.cpp.o

source/scenes/utils/Enemy.i: source/scenes/utils/Enemy.cpp.i
.PHONY : source/scenes/utils/Enemy.i

# target to preprocess a source file
source/scenes/utils/Enemy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/source/scenes/utils/Enemy.cpp.i
.PHONY : source/scenes/utils/Enemy.cpp.i

source/scenes/utils/Enemy.s: source/scenes/utils/Enemy.cpp.s
.PHONY : source/scenes/utils/Enemy.s

# target to generate assembly for a file
source/scenes/utils/Enemy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/source/scenes/utils/Enemy.cpp.s
.PHONY : source/scenes/utils/Enemy.cpp.s

source/scenes/utils/FontLoader.o: source/scenes/utils/FontLoader.cpp.o
.PHONY : source/scenes/utils/FontLoader.o

# target to build an object file
source/scenes/utils/FontLoader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/source/scenes/utils/FontLoader.cpp.o
.PHONY : source/scenes/utils/FontLoader.cpp.o

source/scenes/utils/FontLoader.i: source/scenes/utils/FontLoader.cpp.i
.PHONY : source/scenes/utils/FontLoader.i

# target to preprocess a source file
source/scenes/utils/FontLoader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/source/scenes/utils/FontLoader.cpp.i
.PHONY : source/scenes/utils/FontLoader.cpp.i

source/scenes/utils/FontLoader.s: source/scenes/utils/FontLoader.cpp.s
.PHONY : source/scenes/utils/FontLoader.s

# target to generate assembly for a file
source/scenes/utils/FontLoader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/source/scenes/utils/FontLoader.cpp.s
.PHONY : source/scenes/utils/FontLoader.cpp.s

source/scenes/utils/ParallaxBackground.o: source/scenes/utils/ParallaxBackground.cpp.o
.PHONY : source/scenes/utils/ParallaxBackground.o

# target to build an object file
source/scenes/utils/ParallaxBackground.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/source/scenes/utils/ParallaxBackground.cpp.o
.PHONY : source/scenes/utils/ParallaxBackground.cpp.o

source/scenes/utils/ParallaxBackground.i: source/scenes/utils/ParallaxBackground.cpp.i
.PHONY : source/scenes/utils/ParallaxBackground.i

# target to preprocess a source file
source/scenes/utils/ParallaxBackground.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/source/scenes/utils/ParallaxBackground.cpp.i
.PHONY : source/scenes/utils/ParallaxBackground.cpp.i

source/scenes/utils/ParallaxBackground.s: source/scenes/utils/ParallaxBackground.cpp.s
.PHONY : source/scenes/utils/ParallaxBackground.s

# target to generate assembly for a file
source/scenes/utils/ParallaxBackground.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/source/scenes/utils/ParallaxBackground.cpp.s
.PHONY : source/scenes/utils/ParallaxBackground.cpp.s

source/scenes/utils/Player.o: source/scenes/utils/Player.cpp.o
.PHONY : source/scenes/utils/Player.o

# target to build an object file
source/scenes/utils/Player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/source/scenes/utils/Player.cpp.o
.PHONY : source/scenes/utils/Player.cpp.o

source/scenes/utils/Player.i: source/scenes/utils/Player.cpp.i
.PHONY : source/scenes/utils/Player.i

# target to preprocess a source file
source/scenes/utils/Player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/source/scenes/utils/Player.cpp.i
.PHONY : source/scenes/utils/Player.cpp.i

source/scenes/utils/Player.s: source/scenes/utils/Player.cpp.s
.PHONY : source/scenes/utils/Player.s

# target to generate assembly for a file
source/scenes/utils/Player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/source/scenes/utils/Player.cpp.s
.PHONY : source/scenes/utils/Player.cpp.s

source/scenes/utils/StaticTile.o: source/scenes/utils/StaticTile.cpp.o
.PHONY : source/scenes/utils/StaticTile.o

# target to build an object file
source/scenes/utils/StaticTile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/source/scenes/utils/StaticTile.cpp.o
.PHONY : source/scenes/utils/StaticTile.cpp.o

source/scenes/utils/StaticTile.i: source/scenes/utils/StaticTile.cpp.i
.PHONY : source/scenes/utils/StaticTile.i

# target to preprocess a source file
source/scenes/utils/StaticTile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/source/scenes/utils/StaticTile.cpp.i
.PHONY : source/scenes/utils/StaticTile.cpp.i

source/scenes/utils/StaticTile.s: source/scenes/utils/StaticTile.cpp.s
.PHONY : source/scenes/utils/StaticTile.s

# target to generate assembly for a file
source/scenes/utils/StaticTile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/source/scenes/utils/StaticTile.cpp.s
.PHONY : source/scenes/utils/StaticTile.cpp.s

source/scenes/utils/TextureLoader.o: source/scenes/utils/TextureLoader.cpp.o
.PHONY : source/scenes/utils/TextureLoader.o

# target to build an object file
source/scenes/utils/TextureLoader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/source/scenes/utils/TextureLoader.cpp.o
.PHONY : source/scenes/utils/TextureLoader.cpp.o

source/scenes/utils/TextureLoader.i: source/scenes/utils/TextureLoader.cpp.i
.PHONY : source/scenes/utils/TextureLoader.i

# target to preprocess a source file
source/scenes/utils/TextureLoader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/source/scenes/utils/TextureLoader.cpp.i
.PHONY : source/scenes/utils/TextureLoader.cpp.i

source/scenes/utils/TextureLoader.s: source/scenes/utils/TextureLoader.cpp.s
.PHONY : source/scenes/utils/TextureLoader.s

# target to generate assembly for a file
source/scenes/utils/TextureLoader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/source/scenes/utils/TextureLoader.cpp.s
.PHONY : source/scenes/utils/TextureLoader.cpp.s

source/scenes/utils/Tile.o: source/scenes/utils/Tile.cpp.o
.PHONY : source/scenes/utils/Tile.o

# target to build an object file
source/scenes/utils/Tile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/source/scenes/utils/Tile.cpp.o
.PHONY : source/scenes/utils/Tile.cpp.o

source/scenes/utils/Tile.i: source/scenes/utils/Tile.cpp.i
.PHONY : source/scenes/utils/Tile.i

# target to preprocess a source file
source/scenes/utils/Tile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/source/scenes/utils/Tile.cpp.i
.PHONY : source/scenes/utils/Tile.cpp.i

source/scenes/utils/Tile.s: source/scenes/utils/Tile.cpp.s
.PHONY : source/scenes/utils/Tile.s

# target to generate assembly for a file
source/scenes/utils/Tile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/source/scenes/utils/Tile.cpp.s
.PHONY : source/scenes/utils/Tile.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... game"
	@echo "... sfml-audio"
	@echo "... sfml-graphics"
	@echo "... sfml-network"
	@echo "... sfml-system"
	@echo "... sfml-window"
	@echo "... source/main.o"
	@echo "... source/main.i"
	@echo "... source/main.s"
	@echo "... source/scenes/Character.o"
	@echo "... source/scenes/Character.i"
	@echo "... source/scenes/Character.s"
	@echo "... source/scenes/Game.o"
	@echo "... source/scenes/Game.i"
	@echo "... source/scenes/Game.s"
	@echo "... source/scenes/title_screen.o"
	@echo "... source/scenes/title_screen.i"
	@echo "... source/scenes/title_screen.s"
	@echo "... source/scenes/utils/AnimatedObject.o"
	@echo "... source/scenes/utils/AnimatedObject.i"
	@echo "... source/scenes/utils/AnimatedObject.s"
	@echo "... source/scenes/utils/Button.o"
	@echo "... source/scenes/utils/Button.i"
	@echo "... source/scenes/utils/Button.s"
	@echo "... source/scenes/utils/CollisionElement.o"
	@echo "... source/scenes/utils/CollisionElement.i"
	@echo "... source/scenes/utils/CollisionElement.s"
	@echo "... source/scenes/utils/DrawnButton.o"
	@echo "... source/scenes/utils/DrawnButton.i"
	@echo "... source/scenes/utils/DrawnButton.s"
	@echo "... source/scenes/utils/DrawnImage.o"
	@echo "... source/scenes/utils/DrawnImage.i"
	@echo "... source/scenes/utils/DrawnImage.s"
	@echo "... source/scenes/utils/DrawnText.o"
	@echo "... source/scenes/utils/DrawnText.i"
	@echo "... source/scenes/utils/DrawnText.s"
	@echo "... source/scenes/utils/DynamicTile.o"
	@echo "... source/scenes/utils/DynamicTile.i"
	@echo "... source/scenes/utils/DynamicTile.s"
	@echo "... source/scenes/utils/Enemy.o"
	@echo "... source/scenes/utils/Enemy.i"
	@echo "... source/scenes/utils/Enemy.s"
	@echo "... source/scenes/utils/FontLoader.o"
	@echo "... source/scenes/utils/FontLoader.i"
	@echo "... source/scenes/utils/FontLoader.s"
	@echo "... source/scenes/utils/ParallaxBackground.o"
	@echo "... source/scenes/utils/ParallaxBackground.i"
	@echo "... source/scenes/utils/ParallaxBackground.s"
	@echo "... source/scenes/utils/Player.o"
	@echo "... source/scenes/utils/Player.i"
	@echo "... source/scenes/utils/Player.s"
	@echo "... source/scenes/utils/StaticTile.o"
	@echo "... source/scenes/utils/StaticTile.i"
	@echo "... source/scenes/utils/StaticTile.s"
	@echo "... source/scenes/utils/TextureLoader.o"
	@echo "... source/scenes/utils/TextureLoader.i"
	@echo "... source/scenes/utils/TextureLoader.s"
	@echo "... source/scenes/utils/Tile.o"
	@echo "... source/scenes/utils/Tile.i"
	@echo "... source/scenes/utils/Tile.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

